from fastapi import FastAPI
app = FastAPI()

peliculas = [
    {"Título": "El Padrino", "Género": "Drama", "Año": "1972"  },
    {"Título": "Titanic", "Género": "Romance", "Año": "1997"  },
    {"Título": "Star Wars: Episodio IV", "Género": "Ciencia ficción", "Año": "1977"  },
    {"Título": "El Señor de los Anillos: La Comunidad del Anillo", "Género": "Fantasía", "Año": "2001"  },
    {"Título": "Matrix", "Género": "Acción", "Año": "1999"  },
    {"Título": "Toy Story", "Género": "Animación", "Año": "1995"  },
    {"Título": "Jurassic Park", "Género": "Aventura", "Año": "1993"  },
    {"Título": "Avengers: Endgame", "Género": "Superhéroes", "Año": "2019"  },
    {"Título": "El Rey León", "Género": "Animación", "Año": "1994"  },
    {"Título": "Regreso al Futuro", "Género": "Ciencia ficción", "Año": "1985"  },
    {"Título": "Harry Potter y la Piedra Filosofal", "Género": "Fantasía", "Año": "2001"  },
    {"Título": "Forrest Gump", "Género": "Drama", "Año": "1994"  },
    {"Título": "El Rey León", "Género": "Animación", "Año": "1994"  },
    {"Título": "Los Vengadores", "Género": "Superhéroes", "Año": "2012"  },
    {"Título": "La La Land", "Género": "Musical", "Año": "2016"  },
    {"Título": "Pulp Fiction", "Género": "Crimen", "Año": "1994"  },
    {"Título": "El Resplandor", "Género": "Terror", "Año": "1980"  },
    {"Título": "E.T. el Extraterrestre", "Género": "Ciencia ficción", "Año": "1982"  },
    {"Título": "El Rey León", "Género": "Animación", "Año": "1994"  },
    {"Título": "El Caballero de la Noche", "Género": "Acción", "Año": "2008"  },
    {"Título": "Los Increíbles", "Género": "Animación", "Año": "2004"  },
    {"Título": "El Gran Gatsby", "Género": "Drama", "Año": "2013"  },
    {"Título": "Avatar", "Género": "Ciencia ficción", "Año": "2009"  },
    {"Título": "Gladiador", "Género": "Acción", "Año": "2000"  },
    {"Título": "Cadena Perpetua", "Género": "Drama", "Año": "1994"  },
    {"Título": "El Rey León", "Género": "Animación", "Año": "1994"  },
    {"Título": "El Silencio de los Corderos", "Género": "Suspense", "Año": "1991"  },
    {"Título": "El Club de la Lucha", "Género": "Drama", "Año": "1999"  },
    {"Título": "El Pianista", "Género": "Drama", "Año": "2002"  },
    {"Título": "Volver al Futuro", "Género": "Ciencia ficción", "Año": "1989"  },
    {"Título": "Indiana Jones: En busca del arca perdida", "Género": "Aventura", "Año": "1981"  },
    {"Título": "El Rey León", "Género": "Animación", "Año": "1994"  },
    {"Título": "La Forma del Agua", "Género": "Fantasía", "Año": "2017"  },
    {"Título": "Interestelar", "Género": "Ciencia ficción", "Año": "2014"  },
    {"Título": "La Lista de Schindler", "Género": "Drama", "Año": "1993"  },
    {"Título": "Misión: Imposible", "Género": "Acción", "Año": "1996"  },
    {"Título": "El Rey León", "Género": "Animación", "Año": "1994"  },
    {"Título": "La Red Social", "Género": "Drama", "Año": "2010"  },
    {"Título": "Los Juegos del Hambre", "Género": "Aventura", "Año": "2012"  },
    {"Título": "Shrek", "Género": "Animación", "Año": "2001"  },
    {"Título": "El Rey León", "Género": "Animación", "Año": "1994"  },
    {"Título": "El Renacido", "Género": "Aventura", "Año": "2015"  },
    {"Título": "La Guerra de las Galaxias: El Imperio Contraataca", "Género": "Ciencia ficción", "Año": "1980"  },
    {"Título": "El Laberinto del Fauno", "Género": "Fantasía", "Año": "2006"  },
    {"Título": "Gladiator", "Género": "Acción", "Año": "2000"  },
    {"Título": "Psicosis", "Género": "Terror", "Año": "1960"  },
    {"Título": "Toy Story", "Género": "Animación", "Año": "1995"  },
    {"Título": "El Señor de los Anillos: El Retorno del Rey", "Género": "Fantasía", "Año": "2003"  },
    {"Título": "Interestelar", "Género": "Ciencia ficción", "Año": "2014"  },
    {"Título": "Piratas del Caribe: La Maldición del Perla Negra", "Género": "Aventura", "Año": "2003"  },
    {"Título": "El Cisne Negro", "Género": "Drama", "Año": "2010"  },
    {"Título": "Up", "Género": "Animación", "Año": "2009"  },
    {"Título": "El Padrino: Parte II", "Género": "Drama", "Año": "1974"  },
    {"Título": "Mad Max: Furia en el Camino", "Género": "Acción", "Año": "2015"  },
    {"Título": "Los Vengadores: Infinity War", "Género": "Superhéroes", "Año": "2018"  },
    {"Título": "El Club de la Pelea", "Género": "Drama", "Año": "1999"  },
    {"Título": "La Bella y la Bestia", "Género": "Animación", "Año": "1991"  },
    {"Título": "El Discurso del Rey", "Género": "Drama", "Año": "2010"  },
    {"Título": "Avatar", "Género": "Ciencia ficción", "Año": "2009"  },
    {"Título": "Los Juegos del Hambre: En Llamas", "Género": "Aventura", "Año": "2013"  },
    {"Título": "Cómo Entrenar a tu Dragón", "Género": "Animación", "Año": "2010"  },
    {"Título": "El Club de la Lucha", "Género": "Drama", "Año": "1999"  },
    {"Título": "El Resplandor", "Género": "Terror", "Año": "1980"  },
    {"Título": "Interestelar", "Género": "Ciencia ficción", "Año": "2014"  },
    {"Título": "El Silencio de los Corderos", "Género": "Suspense", "Año": "1991"  },
    {"Título": "El Gran Gatsby", "Género": "Drama", "Año": "2013"  },
    {"Título": "Misión: Imposible", "Género": "Acción", "Año": "1996"  },
    {"Título": "Cadena Perpetua", "Género": "Drama", "Año": "1994"  },
    {"Título": "El Señor de los Anillos: Las Dos Torres", "Género": "Fantasía", "Año": "2002"  },
    {"Título": "La Vida es Bella", "Género": "Drama", "Año": "1997"  },
    {"Título": "El Padrino: Parte III", "Género": "Drama", "Año": "1990"  },
    {"Título": "Harry Potter y la Cámara Secreta", "Género": "Fantasía", "Año": "2002"  },
    {"Título": "Los Increíbles", "Género": "Animación", "Año": "2004"  },
    {"Título": "El Renacido", "Género": "Aventura", "Año": "2015"  },
    {"Título": "El Club de la Pelea", "Género": "Drama", "Año": "1999"  },
    {"Título": "Pulp Fiction", "Género": "Crimen", "Año": "1994"  },
    {"Título": "Shrek", "Género": "Animación", "Año": "2001"  },
    {"Título": "El Rey León", "Género": "Animación", "Año": "1994"  },
    {"Título": "Avatar", "Género": "Ciencia ficción", "Año": "2009"  },
    {"Título": "El Señor de los Anillos: El Retorno del Rey", "Género": "Fantasía", "Año": "2003"  },
    {"Título": "Toy Story", "Género": "Animación", "Año": "1995"  },
    {"Título": "La La Land", "Género": "Musical", "Año": "2016" },
    {"Título": "El Silencio de los Corderos", "Género": "Suspense", "Año": "1991" },
    {"Título": "El Pianista", "Género": "Drama", "Año": "2002" },
    {"Título": "Indiana Jones: En busca del arca perdida", "Género": "Aventura", "Año": "1981" },
    {"Título": "Forrest Gump", "Género": "Drama", "Año": "1994" },
    {"Título": "Interestelar", "Género": "Ciencia ficción", "Año": "2014" },
    {"Título": "El Club de la Lucha", "Género": "Drama", "Año": "1999" },
    {"Título": "Mad Max: Furia en el Camino", "Género": "Acción", "Año": "2015" },
    {"Título": "El Renacido", "Género": "Aventura", "Año": "2015" },
    {"Título": "El Rey León", "Género": "Animación", "Año": "1994" },
    {"Título": "Los Juegos del Hambre: En Llamas", "Género": "Aventura", "Año": "2013" },
    {"Título": "La Forma del Agua", "Género": "Fantasía", "Año": "2017" },
    {"Título": "El Señor de los Anillos: Las Dos Torres", "Género": "Fantasía", "Año": "2002" },
    {"Título": "Gladiator", "Género": "Acción", "Año": "2000" },
    {"Título": "El Cisne Negro", "Género": "Drama", "Año": "2010" },
    {"Título": "Piratas del Caribe: La Maldición del Perla Negra", "Género": "Aventura", "Año": "2003" },
    {"Título": "Cadena Perpetua", "Género": "Drama", "Año": "1994" },
    {"Título": "El Silencio de los Corderos", "Género": "Suspense", "Año": "1991" },
    {"Título": "El Club de la Pelea", "Género": "Drama", "Año": "1999" },
    {"Título": "La Vida es Bella", "Género": "Drama", "Año": "1997" },
    {"Título": "El Padrino: Parte II", "Género": "Drama", "Año": "1974" },
    {"Título": "Harry Potter y la Cámara Secreta", "Género": "Fantasía", "Año": "2002" },
    {"Título": "Toy Story", "Género": "Animación", "Año": "1995" },
    {"Título": "Los Vengadores: Infinity War", "Género": "Superhéroes", "Año": "2018" },
    {"Título": "El Resplandor", "Género": "Terror", "Año": "1980" },
    {"Título": "El Club de la Lucha", "Género": "Drama", "Año": "1999" },
    {"Título": "Interestelar", "Género": "Ciencia ficción", "Año": "2014" },
    {"Título": "La Bella y la Bestia", "Género": "Animación", "Año": "1991" },
    {"Título": "Psicosis", "Género": "Terror", "Año": "1960" },
    {"Título": "El Laberinto del Fauno", "Género": "Fantasía", "Año": "2006" },
    {"Título": "Piratas del Caribe: La Maldición del Perla Negra", "Género": "Aventura", "Año": "2003" },
    {"Título": "El Discurso del Rey", "Género": "Drama", "Año": "2010" },
    {"Título": "El Renacido", "Género": "Aventura", "Año": "2015" },
    {"Título": "Cadena Perpetua", "Género": "Drama", "Año": "1994" },
    {"Título": "El Pianista", "Género": "Drama", "Año": "2002" },
    {"Título": "Los Increíbles", "Género": "Animación", "Año": "2004" },
    {"Título": "El Caballero de la Noche", "Género": "Acción", "Año": "2008" },
    {"Título": "Forrest Gump", "Género": "Drama", "Año": "1994" },
    {"Título": "Interestelar", "Género": "Ciencia ficción", "Año": "2014" },
    {"Título": "El Señor de los Anillos: El Retorno del Rey", "Género": "Fantasía", "Año": "2003" },
    {"Título": "Toy Story", "Género": "Animación", "Año": "1995" },
    {"Título": "La La Land", "Género": "Musical", "Año": "2016" },
    {"Título": "El Silencio de los Corderos", "Género": "Suspense", "Año": "1991" },
    {"Título": "El Padrino: Parte III", "Género": "Drama", "Año": "1990" },
    {"Título": "Misión: Imposible", "Género": "Acción", "Año": "1996" },
    {"Título": "Pulp Fiction", "Género": "Crimen", "Año": "1994" },
    {"Título": "Shrek", "Género": "Animación", "Año": "2001" },
    {"Título": "El Señor de los Anillos: Las Dos Torres", "Género": "Fantasía", "Año": "2002" },
    {"Título": "La Vida es Bella", "Género": "Drama", "Año": "1997" },
    {"Título": "Gladiator", "Género": "Acción", "Año": "2000" },
    {"Título": "El Resplandor", "Género": "Terror", "Año": "1980" },
    {"Título": "El Laberinto del Fauno", "Género": "Fantasía", "Año": "2006" },
    {"Título": "El Pianista", "Género": "Drama", "Año": "2002" },
    {"Título": "El Rey León", "Género": "Animación", "Año": "1994" },
    {"Título": "Los Vengadores: Infinity War", "Género": "Superhéroes", "Año": "2018" },
    {"Título": "El Club de la Lucha", "Género": "Drama", "Año": "1999" },
    {"Título": "El Renacido", "Género": "Aventura", "Año": "2015" },
    {"Título": "Cadena Perpetua", "Género": "Drama", "Año": "1994" },
    {"Título": "El Discurso del Rey", "Género": "Drama", "Año": "2010" },
    {"Título": "El Gran Gatsby", "Género": "Drama", "Año": "2013" },
    {"Título": "El Rey León", "Género": "Animación", "Año": "1994" },
    {"Título": "Avatar", "Género": "Ciencia ficción", "Año": "2009" },
    {"Título": "Interestelar", "Género": "Ciencia ficción", "Año": "2014" },
    {"Título": "El Silencio de los Corderos", "Género": "Suspense", "Año": "1991" },
    {"Título": "El Club de la Pelea", "Género": "Drama", "Año": "1999" },
    {"Título": "La Bella y la Bestia", "Género": "Animación", "Año": "1991" },
    {"Título": "Psicosis", "Género": "Terror", "Año": "1960" },
    {"Título": "El Laberinto del Fauno", "Género": "Fantasía", "Año": "2006" },
    {"Título": "Gladiator", "Género": "Acción", "Año": "2000" },
    {"Título": "Toy Story", "Género": "Animación", "Año": "1995" },
    {"Título": "El Señor de los Anillos: El Retorno del Rey", "Género": "Fantasía", "Año": "2003" },
    {"Título": "La Vida es Bella", "Género": "Drama", "Año": "1997" },
    {"Título": "El Padrino: Parte II", "Género": "Drama", "Año": "1974" },
    {"Título": "Harry Potter y la Cámara Secreta", "Género": "Fantasía", "Año": "2002" },
    {"Título": "Los Increíbles", "Género": "Animación", "Año": "2004" },
    {"Título": "El Cisne Negro", "Género": "Drama", "Año": "2010" },
    {"Título": "El Caballero de la Noche", "Género": "Acción", "Año": "2008" },
    {"Título": "Forrest Gump", "Género": "Drama", "Año": "1994" },
    {"Título": "Interestelar", "Género": "Ciencia ficción", "Año": "2014" },
    {"Título": "El Club de la Lucha", "Género": "Drama", "Año": "1999" },
    {"Título": "Mad Max: Furia en el Camino", "Género": "Acción", "Año": "2015" },
    {"Título": "El Renacido", "Género": "Aventura", "Año": "2015" },
    {"Título": "El Rey León", "Género": "Animación", "Año": "1994" },
    {"Título": "Los Juegos del Hambre: En Llamas", "Género": "Aventura", "Año": "2013" },
    {"Título": "Cómo Entrenar a tu Dragón", "Género": "Animación", "Año": "2010" },
    {"Título": "El Club de la Lucha", "Género": "Drama", "Año": "1999" },
    {"Título": "El Resplandor", "Género": "Terror", "Año": "1980" },
    {"Título": "Interestelar", "Género": "Ciencia ficción", "Año": "2014" },
    {"Título": "El Silencio de los Corderos", "Género": "Suspense", "Año": "1991" },
    {"Título": "El Pianista", "Género": "Drama", "Año": "2002" },
    {"Título": "Indiana Jones: En busca del arca perdida", "Género": "Aventura", "Año": "1981" },
    {"Título": "Forrest Gump", "Género": "Drama", "Año": "1994" },
    {"Título": "Interestelar", "Género": "Ciencia ficción", "Año": "2014" },
    {"Título": "El Señor de los Anillos: El Retorno del Rey", "Género": "Fantasía", "Año": "2003" },
    {"Título": "Toy Story", "Género": "Animación", "Año": "1995" },
    {"Título": "La La Land", "Género": "Musical", "Año": "2016" },
    {"Título": "El Silencio de los Corderos", "Género": "Suspense", "Año": "1991" },
    {"Título": "El Padrino: Parte III", "Género": "Drama", "Año": "1990" },
    {"Título": "Misión: Imposible", "Género": "Acción", "Año": "1996" },
    {"Título": "Pulp Fiction", "Género": "Crimen", "Año": "1994" },
    {"Título": "Shrek", "Género": "Animación", "Año": "2001" },
    {"Título": "El Señor de los Anillos: Las Dos Torres", "Género": "Fantasía", "Año": "2002" },
    {"Título": "La Vida es Bella", "Género": "Drama", "Año": "1997" },
    {"Título": "Gladiator", "Género": "Acción", "Año": "2000" },
    {"Título": "El Resplandor", "Género": "Terror", "Año": "1980" },
    {"Título": "El Laberinto del Fauno", "Género": "Fantasía", "Año": "2006" },
    {"Título": "El Pianista", "Género": "Drama", "Año": "2002" },
    {"Título": "El Rey León", "Género": "Animación", "Año": "1994" },
    {"Título": "Los Vengadores: Infinity War", "Género": "Superhéroes", "Año": "2018" },
    {"Título": "El Club de la Lucha", "Género": "Drama", "Año": "1999" },
    {"Título": "El Renacido", "Género": "Aventura", "Año": "2015" },
    {"Título": "Cadena Perpetua", "Género": "Drama", "Año": "1994" },
    {"Título": "El Discurso del Rey", "Género": "Drama", "Año": "2010"  },
    {"Título": "El Gran Gatsby", "Género": "Drama", "Año": "2013"  },
    {"Título": "El Rey León", "Género": "Animación", "Año": "1994"  },
    {"Título": "Avatar", "Género": "Ciencia ficción", "Año": "2009"  },
    {"Título": "Interestelar", "Género": "Ciencia ficción", "Año": "2014"  },
    {"Título": "El Silencio de los Corderos", "Género": "Suspense", "Año": "1991"  },
    {"Título": "El Club de la Pelea", "Género": "Drama", "Año": "1999"  },
    ]            

@app.get("/peliculas")
async def imprimir():
    return peliculas

@app.get("/peliculas/{title}")
async def get_movies_by_title(title: str):
    filtered_movies = [movie for movie in peliculas if movie["Título"] == title]
    return filtered_movies


@app.get("/peliculas/titulo/{genre}")
async def get_movies_by_genre(genre: str):
    filtered_movies = [movie for movie in peliculas if movie["Género"] == genre]
    return filtered_movies


@app.get("/peliculas/titulo/genero/{year}")
async def get_movies_by_year(year: str):
    filtered_movies = [movie for movie in peliculas if movie["Año"] == year]
    return filtered_movies

